# Generated by Django 5.1.5 on 2025-02-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='telephone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('plastic', 'Plastic'), ('rubber', 'Rubber'), ('tin', 'Tin'), ('old_cloths', 'Old Cloths'), ('metal', 'Metal'), ('paper', 'Paper'), ('other', 'Other')], default='plastic', max_length=20),
        ),
    ]
